"""
ML Metadata Database Models
Tracks all automated notebook runs and predictions
"""

from sqlalchemy import Column, Integer, String, Float, DateTime, JSON, Text
from sqlalchemy.sql import func
from app.db.base import Base

class MLJobLog(Base):
    """Tracks each automated notebook execution"""
    __tablename__ = "ml_job_logs"
    
    id = Column(Integer, primary_key=True, index=True)
    job_name = Column(String(100), nullable=False, index=True)
    status = Column(String(20), nullable=False)  # success, failed, running
    duration_seconds = Column(Float)
    accuracy = Column(Float, nullable=True)
    metrics = Column(JSON, default={})
    error_message = Column(Text, nullable=True)
    started_at = Column(DateTime(timezone=True), server_default=func.now())
    completed_at = Column(DateTime(timezone=True), nullable=True)


class MLPrediction(Base):
    """Stores predictions generated by notebooks"""
    __tablename__ = "ml_predictions"
    
    id = Column(Integer, primary_key=True, index=True)
    prediction_type = Column(String(50), nullable=False)  # price, risk, demand
    crop_type = Column(String(50), nullable=True)
    location = Column(String(100), nullable=True)
    user_id = Column(Integer, nullable=True)
    predicted_value = Column(Float, nullable=False)
    confidence = Column(Float, default=0.85)
    valid_until = Column(DateTime(timezone=True), nullable=False)
    extended_metadata = Column(JSON, default={})
    created_at = Column(DateTime(timezone=True), server_default=func.now())


class MLInsight(Base):
    """Stores insights generated by notebooks"""
    __tablename__ = "ml_insights"
    
    id = Column(Integer, primary_key=True, index=True)
    insight_type = Column(String(50), nullable=False)
    content = Column(Text, nullable=False)
    priority = Column(String(20), default='normal')  # high, normal, low
    is_viewed = Column(Integer, default=0)
    created_at = Column(DateTime(timezone=True), server_default=func.now())


class ModelVersion(Base):
    """Tracks model versions deployed"""
    __tablename__ = "model_versions"
    
    id = Column(Integer, primary_key=True, index=True)
    model_name = Column(String(100), nullable=False)
    version = Column(String(20), nullable=False)
    file_path = Column(String(500), nullable=False)
    accuracy = Column(Float)
    is_active = Column(Integer, default=1)
    deployed_at = Column(DateTime(timezone=True), server_default=func.now())
