export const theme = {
  colors: {
    sky: '#0C7BEF',
    gold: '#D9A441',
    black: '#15212E',
    dark: '#15212E',
    light: '#F7F2E8',
    white: '#FFFFFF',
    cream: '#FAF7F1',
    danger: '#C94242',
    secondary: '#1F6F43',
    successTint: '#E9F6EF',
    infoTint: '#ECF4FF',
    gray: {
      100: '#F8FAFC',
      200: '#EEF2F6',
      300: '#D7DEE8',
      400: '#A8B4C3',
      500: '#7B8898',
      600: '#5D6978',
      700: '#455160',
      800: '#2B3645',
      900: '#16202C',
    },
  },
  typography: {
    h1: { fontSize: 34, fontWeight: '800', letterSpacing: -0.6, lineHeight: 40 },
    h2: { fontSize: 29, fontWeight: '800', letterSpacing: -0.4, lineHeight: 35 },
    h3: { fontSize: 24, fontWeight: '700', letterSpacing: -0.2, lineHeight: 30 },
    h4: { fontSize: 20, fontWeight: '700', letterSpacing: -0.1, lineHeight: 26 },
    body: { fontSize: 16, fontWeight: '500', lineHeight: 24 },
    bodyLarge: { fontSize: 18, fontWeight: '500', lineHeight: 28 },
    caption: { fontSize: 14, fontWeight: '500', lineHeight: 20 },
    small: { fontSize: 12, fontWeight: '500', lineHeight: 16 },
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
    xxl: 48,
  },
  borderRadius: {
    xs: 4,
    sm: 10,
    md: 14,
    lg: 20,
    xl: 24,
    xxl: 30,
    round: 9999,
  },
  shadows: {
    xs: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.05,
      shadowRadius: 2,
      elevation: 1,
    },
    sm: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.06,
      shadowRadius: 6,
      elevation: 2,
    },
    md: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.1,
      shadowRadius: 14,
      elevation: 6,
    },
    lg: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 12 },
      shadowOpacity: 0.14,
      shadowRadius: 20,
      elevation: 10,
    },
    xl: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: 0.2,
      shadowRadius: 20,
      elevation: 12,
    },
  },
};

const styles = {
  text: { color: theme.colors.black },
  view: { backgroundColor: theme.colors.gray[100] },
  button: { backgroundColor: theme.colors.sky, paddingVertical: 18, paddingHorizontal: 32, borderRadius: theme.borderRadius.lg, ...theme.shadows.md },
  buttonText: { color: theme.colors.white, fontWeight: '800', fontSize: 16, letterSpacing: 0.4 },
  input: { borderWidth: 1, borderColor: theme.colors.gray[200], paddingVertical: 16, paddingHorizontal: 18, borderRadius: theme.borderRadius.lg, backgroundColor: theme.colors.white, fontSize: 16, fontWeight: '500', ...theme.shadows.xs },
};

export { styles };
