import random
from typing import List, Dict

class AcademyService:
    QUESTION_POOL = [
        {
            "id": 1,
            "question": "If a farmer offers you a $20 'acceleration fee' to skip a test, what is the correct action?",
            "options": [
                "Accept it to help with fuel costs",
                "Skip the test but note it privately",
                "Refuse and file a Governance Red-Flag",
                "Accept it and report it later"
            ],
            "correct": 2
        },
        {
            "id": 2,
            "question": "What is the maximum allowable moisture for certified Grade A Maize for storage?",
            "options": ["14.5%", "13.0%", "12.5%", "11.0%"],
            "correct": 2
        },
        {
            "id": 3,
            "question": "A buyer claims the product delivered does not match your verification. What is your role?",
            "options": [
                "Sides with the farmer",
                "Sides with the buyer",
                "Act as a neutral arbiter and re-verify",
                "Call the police immediately"
            ],
            "correct": 2
        },
        {
            "id": 4,
            "question": "The AgriTrust app prevents verification if your GPS is more than how far from the listing location?",
            "options": ["10m", "50m", "100m", "500m"],
            "correct": 1
        },
        {
            "id": 5,
            "question": "Which of these is NOT a primary responsibility of a Field Agent?",
            "options": [
                "Ground Truth verification",
                "Regional price manipulation",
                "Farmer onboarding and support",
                "Delivery confirmation"
            ],
            "correct": 1
        },
        {
            "id": 6,
            "question": "In the AgriTrust ecosystem, what does ZiG represent?",
            "options": ["Zimbabwe Gold (Local Currency)", "Zimbabwe Grain", "Zone Intelligence Gate", "Zero Internal Growth"],
            "correct": 0
        },
        {
            "id": 7,
            "question": "When should you release Escrow funds to a seller?",
            "options": [
                "As soon as the listing is verified",
                "When the buyer pays the deposit",
                "Only after successful delivery and verification",
                "When the farmer asks for it"
            ],
            "correct": 2
        },
        {
            "id": 8,
            "question": "What happens if a Grade verification fail repeatedly on the same farm?",
            "options": [
                "The agent is fired",
                "A system audit is triggered and trust scores are frozen",
                "The farmer is banned immediately",
                "Nothing, it's normal"
            ],
            "correct": 1
        },
        {
            "id": 9,
            "question": "How do you confirm a secure handover of physical goods?",
            "options": [
                "A handshake and a photo",
                "Entering a unique One-Time-Code generated by the buyer",
                "Signing a paper manifest only",
                "Verifying the buyer's ID card"
            ],
            "correct": 1
        },
        {
            "id": 10,
            "question": "What is the primary method for resolving a logistics dispute?",
            "options": [
                "Marketplace-led mediation with Escrow override",
                "Private negotiation between parties",
                "Refunding the buyer immediately",
                "Ignoring it until 30 days pass"
            ],
            "correct": 0
        },
        {
            "id": 11,
            "question": "ZIMBABWE LAWS: Which act governs the protection of personal farmer data collected by AgriTrust agents?",
            "options": [
                "Agricultural Marketing Authority Act",
                "Data Protection Act [Chapter 11:12]",
                "Public Health Act",
                "Regional Town and Country Planning Act"
            ],
            "correct": 1
        },
        {
            "id": 12,
            "question": "ETHICS: A prominent buyer asks for a 'back-channel' list of all farmers with Grade A tobacco before it goes live. You should:",
            "options": [
                "Provide it to build the relationship",
                "Provide it for a consulting fee",
                "Refuse and report it to the Trust Governance Board",
                "Tell them you'll do it if they buy from you later"
            ],
            "correct": 2
        },
        {
            "id": 13,
            "question": "CROP GRADING: You observe 'weevil boreholes' in 2% of the maize sample. According to Module 3, this maize is:",
            "options": [
                "Grade A (Export Quality)",
                "Grade B (Standard Market)",
                "Grade C (Industrial/Animal Feed)",
                "Rejected (Zero Value)"
            ],
            "correct": 2
        },
        {
            "id": 14,
            "question": "ESCROW: A farmer claims they delivered 50kg, but the buyer's scale shows 48kg. The correct procedure is:",
            "options": [
                "Release funds based on the farmer's invoice",
                "Refund the buyer immediately",
                "Perform an on-site 'Ground-Truth' re-weigh with a certified scale",
                "Split the difference manually without verification"
            ],
            "correct": 2
        },
        {
            "id": 15,
            "question": "FINANCE: What is the maximum response time allowed for an agent to verify a loan application request?",
            "options": ["2 hours", "12 hours", "24 hours", "48 hours"],
            "correct": 2
        }
    ]

    @staticmethod
    def get_random_exam(count: int = 10) -> List[Dict]:
        """Fetch a randomized set of questions for testing (Master Plan: 200 Qs for Final)"""
        return random.sample(AcademyService.QUESTION_POOL, min(count, len(AcademyService.QUESTION_POOL)))

    @staticmethod
    def grade_exam(submission: Dict[int, int]) -> Dict:
        """
        submission: { question_id: selected_option_index }
        """
        correct_count = 0
        results = []
        
        for q_id, selected in submission.items():
            question = next((q for q in AcademyService.QUESTION_POOL if q["id"] == int(q_id)), None)
            if question:
                is_correct = question["correct"] == selected
                if is_correct:
                    correct_count += 1
                results.append({
                    "id": q_id,
                    "is_correct": is_correct,
                    "correct_index": question["correct"],
                    "explanation": question["options"][question["correct"]]
                })
        
        score_percent = (correct_count / len(submission)) * 100 if submission else 0
        return {
            "score": round(score_percent, 1),
            "passed": score_percent >= 80.0, # MASTER PLAN THRESHOLD: 80% REQUIRED
            "results": results
        }

academy_service = AcademyService()
