"""Add verification models

Revision ID: 51f1bf200556
Revises: 0032
Create Date: 2026-05-17 21:52:51.313767

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '51f1bf200556'
down_revision = '0032'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_verification_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.Enum('NATIONAL_ID', 'PASSPORT', 'DRIVERS_LICENSE', 'PROOF_OF_ADDRESS', 'FARM_REGISTRATION', 'BUSINESS_REGISTRATION', 'TAX_CLEARANCE', 'AGENT_APPLICATION', 'VEHICLE_REGISTRATION', name='documenttype'), nullable=False),
    sa.Column('document_label', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('PENDING_AGENT', 'PENDING_ADMIN', 'UNDER_REVIEW', 'APPROVED', 'REJECTED', 'EXPIRED', 'RESUBMISSION_REQUESTED', name='verificationstatus'), nullable=False),
    sa.Column('current_stage', sa.String(length=50), nullable=False),
    sa.Column('required_reviewer_role', sa.Enum('AGENT', 'ADMIN', 'SUPER_ADMIN', name='reviewerrole'), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('back_file_url', sa.String(length=500), nullable=True),
    sa.Column('selfie_file_url', sa.String(length=500), nullable=True),
    sa.Column('supporting_file_url', sa.String(length=500), nullable=True),
    sa.Column('document_number', sa.String(length=100), nullable=True),
    sa.Column('issuing_authority', sa.String(length=100), nullable=True),
    sa.Column('issue_date', sa.DateTime(), nullable=True),
    sa.Column('expiry_date', sa.DateTime(), nullable=True),
    sa.Column('fraud_score', sa.Float(), nullable=False),
    sa.Column('fraud_flags', sa.JSON(), nullable=False),
    sa.Column('duplicate_check_passed', sa.Boolean(), nullable=False),
    sa.Column('auto_screen_score', sa.Float(), nullable=False),
    sa.Column('auto_screen_passed', sa.Boolean(), nullable=False),
    sa.Column('manual_review_required', sa.Boolean(), nullable=False),
    sa.Column('agent_reviewer_id', sa.UUID(), nullable=True),
    sa.Column('agent_reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('agent_decision', sa.String(length=20), nullable=True),
    sa.Column('agent_notes', sa.Text(), nullable=True),
    sa.Column('admin_reviewer_id', sa.UUID(), nullable=True),
    sa.Column('admin_reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('admin_decision', sa.String(length=20), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('resubmission_count', sa.Integer(), nullable=False),
    sa.Column('max_resubmissions', sa.Integer(), nullable=False),
    sa.Column('resubmission_deadline', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('rejection_category', sa.String(length=50), nullable=True),
    sa.Column('trust_score_delta', sa.Integer(), nullable=False),
    sa.Column('trust_score_applied', sa.Boolean(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admin_reviewer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['agent_reviewer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_verification_records_user_id'), 'document_verification_records', ['user_id'], unique=False)
    op.create_table('user_verification_summaries',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('overall_status', sa.Enum('PENDING_AGENT', 'PENDING_ADMIN', 'UNDER_REVIEW', 'APPROVED', 'REJECTED', 'EXPIRED', 'RESUBMISSION_REQUESTED', name='verificationstatus'), nullable=False),
    sa.Column('verification_level', sa.Integer(), nullable=False),
    sa.Column('identity_status', sa.Enum('PENDING_AGENT', 'PENDING_ADMIN', 'UNDER_REVIEW', 'APPROVED', 'REJECTED', 'EXPIRED', 'RESUBMISSION_REQUESTED', name='verificationstatus'), nullable=False),
    sa.Column('identity_verified_at', sa.DateTime(), nullable=True),
    sa.Column('identity_document_type', sa.String(length=50), nullable=True),
    sa.Column('can_list_products', sa.Boolean(), nullable=False),
    sa.Column('can_make_purchases', sa.Boolean(), nullable=False),
    sa.Column('can_receive_payments', sa.Boolean(), nullable=False),
    sa.Column('can_access_loans', sa.Boolean(), nullable=False),
    sa.Column('can_use_platform_services', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('verification_audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('actor_role', sa.String(length=20), nullable=False),
    sa.Column('previous_status', sa.String(length=20), nullable=True),
    sa.Column('new_status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['document_verification_records.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('verification_queue',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('priority_score', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['document_verification_records.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id')
    )
    op.alter_column('admin_users', 'role',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'support_admin'::character varying"))
    op.alter_column('admin_users', 'role_level',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('70'))
    op.alter_column('admin_users', 'mfa_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('admin_users', 'hardware_mfa_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('admin_users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_constraint('admin_users_email_key', 'admin_users', type_='unique')
    op.drop_constraint('admin_users_username_key', 'admin_users', type_='unique')
    op.drop_index('idx_admin_users_email', table_name='admin_users')
    op.drop_index('idx_admin_users_username', table_name='admin_users')
    op.create_index(op.f('ix_admin_users_email'), 'admin_users', ['email'], unique=True)
    op.create_index(op.f('ix_admin_users_id'), 'admin_users', ['id'], unique=False)
    op.create_index(op.f('ix_admin_users_username'), 'admin_users', ['username'], unique=True)
    op.alter_column('audit_logs', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'success'::character varying"))
    op.drop_index('idx_audit_action', table_name='audit_logs')
    op.drop_index('idx_audit_admin_id', table_name='audit_logs')
    op.drop_index('idx_audit_checksum', table_name='audit_logs')
    op.drop_index('idx_audit_created_at', table_name='audit_logs')
    op.drop_index('idx_audit_entity', table_name='audit_logs')
    op.drop_index('idx_audit_request_id', table_name='audit_logs')
    op.drop_index('idx_audit_user_id', table_name='audit_logs')
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_admin_id'), 'audit_logs', ['admin_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_checksum'), 'audit_logs', ['checksum'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_request_id'), 'audit_logs', ['request_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.alter_column('broadcast_messages', 'audience',
               existing_type=postgresql.ENUM('all', 'farmers', 'buyers', 'agents', 'drivers', 'regional', name='broadcastaudience'),
               nullable=False,
               existing_server_default=sa.text("'all'::broadcastaudience"))
    op.alter_column('broadcast_messages', 'channels',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('broadcast_messages', 'status',
               existing_type=postgresql.ENUM('pending', 'scheduled', 'sending', 'sent', 'failed', 'cancelled', name='broadcaststatus'),
               nullable=False,
               existing_server_default=sa.text("'pending'::broadcaststatus"))
    op.alter_column('drivers', 'rejection_note',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('drivers', 'reviewed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.create_foreign_key(None, 'drivers', 'users', ['reviewed_by'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'drivers', type_='foreignkey')
    op.alter_column('drivers', 'reviewed_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('drivers', 'rejection_note',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('broadcast_messages', 'status',
               existing_type=postgresql.ENUM('pending', 'scheduled', 'sending', 'sent', 'failed', 'cancelled', name='broadcaststatus'),
               nullable=True,
               existing_server_default=sa.text("'pending'::broadcaststatus"))
    op.alter_column('broadcast_messages', 'channels',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('broadcast_messages', 'audience',
               existing_type=postgresql.ENUM('all', 'farmers', 'buyers', 'agents', 'drivers', 'regional', name='broadcastaudience'),
               nullable=True,
               existing_server_default=sa.text("'all'::broadcastaudience"))
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_request_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_checksum'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_admin_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.create_index('idx_audit_user_id', 'audit_logs', ['user_id'], unique=False)
    op.create_index('idx_audit_request_id', 'audit_logs', ['request_id'], unique=False)
    op.create_index('idx_audit_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index('idx_audit_created_at', 'audit_logs', ['created_at'], unique=False)
    op.create_index('idx_audit_checksum', 'audit_logs', ['checksum'], unique=False)
    op.create_index('idx_audit_admin_id', 'audit_logs', ['admin_id'], unique=False)
    op.create_index('idx_audit_action', 'audit_logs', ['action'], unique=False)
    op.alter_column('audit_logs', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'success'::character varying"))
    op.drop_index(op.f('ix_admin_users_username'), table_name='admin_users')
    op.drop_index(op.f('ix_admin_users_id'), table_name='admin_users')
    op.drop_index(op.f('ix_admin_users_email'), table_name='admin_users')
    op.create_index('idx_admin_users_username', 'admin_users', ['username'], unique=False)
    op.create_index('idx_admin_users_email', 'admin_users', ['email'], unique=False)
    op.create_unique_constraint('admin_users_username_key', 'admin_users', ['username'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint('admin_users_email_key', 'admin_users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('admin_users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('admin_users', 'hardware_mfa_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('admin_users', 'mfa_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('admin_users', 'role_level',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('70'))
    op.alter_column('admin_users', 'role',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'support_admin'::character varying"))
    op.drop_table('verification_queue')
    op.drop_table('verification_audit_logs')
    op.drop_table('user_verification_summaries')
    op.drop_index(op.f('ix_document_verification_records_user_id'), table_name='document_verification_records')
    op.drop_table('document_verification_records')
    # ### end Alembic commands ###
