import React from "react";
import { Link } from "react-router-dom";
import { motion } from "framer-motion";
import { Shield, Lock, Eye, Database, Trash2, Globe, Cookie, UserX } from "lucide-react";

function PrivacyPolicy() {
 const sections = [
 { id: "collect", title: "Information We Collect", icon: Eye },
 { id: "use", title: "How We Use Your Information", icon: Database },
 { id: "share", title: "Information Sharing", icon: Globe },
 { id: "security", title: "Data Security", icon: Lock },
 { id: "retention", title: "Data Retention", icon: Trash2 },
 { id: "rights", title: "Your Rights", icon: UserX },
 { id: "cookies", title: "Cookies & Tracking", icon: Cookie },
 { id: "contact", title: "Contact Us", icon: Shield },
 ];

 return (
 <div className="min-h-screen bg-earth-50">{/* Hero */}
 <section className="bg-gradient-to-br from-primary-700 to-primary-900 text-white py-16 lg:py-24"><div className="container-custom"><motion.div
 initial={{ opacity: 0, y: 20 }}
 animate={{ opacity: 1, y: 0 }}
 className="text-center max-w-3xl mx-auto"
 ><div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-white/10 backdrop-blur-sm mb-6"><Shield className="w-4 h-4" /><span className="text-sm font-medium">Your Privacy Matters</span></div><h1 className="text-4xl md:text-5xl font-bold mb-4">Privacy Policy</h1><p className="text-primary-100">Last updated: May 2026</p></motion.div></div></section>
{/* Content */}
 <section className="py-16"><div></div> className="container-custom"
 <div className="grid lg:grid-cols-4 gap-8">{/* Sidebar */}
 <div className="hidden lg:block"><div className="sticky top-24 bg-white rounded-xl p-6 shadow-sm border border-earth-100"><h3 className="font-semibold text-earth-900 mb-4">Contents</h3><nav className="space-y-2">{sections.map((section) => (
 <a
 key={section.id}
 href={`#${section.id}`}
 className="flex items-center gap-2 px-3 py-2 rounded-lg text-sm text-earth-600 hover:bg-primary-50 hover:text-primary-700 transition-colors"
 ><section.icon className="w-4 h-4" />{section.title}
 </a>))}
 </nav></div></div>
{/* Main Content */}
 <div className="lg:col-span-3"><div className="bg-white rounded-2xl p-8 shadow-sm border border-earth-100"><p className="text-earth-600 mb-8 leading-relaxed">At ZimAgriTrust, your privacy is our priority. This Privacy Policy explains how we collect, 
 use, disclose, and safeguard your information when you use our platform including USSD (*123#), 
 Mobile App, and Web Portal.
 </p>
<div id="collect" className="mb-12 scroll-mt-24"><div className="flex items-center gap-3 mb-4"><div className="w-10 h-10 rounded-lg bg-primary-100 flex items-center justify-center"><Eye className="w-5 h-5 text-primary-600" /></div><h2 className="text-2xl font-bold text-earth-900">1. Information We Collect</h2></div>
 <h3 className="text-lg font-semibold text-earth-800 mb-3">1.1 Personal Information You Provide</h3><ul className="space-y-2 mb-6 text-earth-600"><li className="flex items-start gap-2"><span className="text-primary-500 mt-1">•</span>Name, phone number, email address</li><li className="flex items-start gap-2"><span className="text-primary-500 mt-1">•</span>National ID or passport (for verification)</li><li className="flex items-start gap-2"><span className="text-primary-500 mt-1">•</span>Farm or business location</li><li className="flex items-start gap-2"><span className="text-primary-500 mt-1">•</span>Bank account or mobile money details</li><li className="flex items-start gap-2"><span className="text-primary-500 mt-1">•</span>Transaction history and listings</li><li className="flex items-start gap-2"><span className="text-primary-500 mt-1">•</span>Communications with other users and support</li></ul>
 <h3 className="text-lg font-semibold text-earth-800 mb-3">1.2 Information Automatically Collected</h3><ul className="space-y-2 mb-6 text-earth-600"><li className="flex items-start gap-2"><span className="text-primary-500 mt-1">•</span>Device information (phone model, operating system)</li><li className="flex items-start gap-2"><span className="text-primary-500 mt-1">•</span>IP address and location data (with consent)</li><li className="flex items-start gap-2"><span className="text-primary-500 mt-1">•</span>USSD session data</li><li className="flex items-start gap-2"><span className="text-primary-500 mt-1">•</span>App usage patterns and analytics</li><li className="flex items-start gap-2"><span className="text-primary-500 mt-1">•</span>Photos uploaded for verification</li></ul>
 <div id="use" className="mb-12 scroll-mt-24 pt-8 border-t border-earth-100"><div className="flex items-center gap-3 mb-4"><div className="w-10 h-10 rounded-lg bg-primary-100 flex items-center justify-center"><Database className="w-5 h-5 text-primary-600" /></div><h2 className="text-2xl font-bold text-earth-900">2. How We Use Your Information</h2></div><ul className="space-y-3 text-earth-600"><li className="flex items-start gap-2"><span className="text-primary-500 mt-1">•</span>Facilitate transactions between farmers and buyers</li><li className="flex items-start gap-2"><span className="text-primary-500 mt-1">•</span>Verify your identity and prevent fraud</li><li className="flex items-start gap-2"><span className="text-primary-500 mt-1">•</span>Calculate and display your trust score</li><li className="flex items-start gap-2"><span className="text-primary-500 mt-1">•</span>Improve our services and user experience</li><li className="flex items-start gap-2"><span className="text-primary-500 mt-1">•</span>Send transaction notifications via SMS, WhatsApp, and email</li><li className="flex items-start gap-2"><span className="text-primary-500 mt-1">•</span>Comply with legal and regulatory requirements</li><li className="flex items-start gap-2"><span className="text-primary-500 mt-1">•</span>Resolve disputes and investigate complaints</li></ul></div>
 <div id="share" className="mb-12 scroll-mt-24 pt-8 border-t border-earth-100"><div className="flex items-center gap-3 mb-4"><div className="w-10 h-10 rounded-lg bg-primary-100 flex items-center justify-center"><Globe className="w-5 h-5 text-primary-600" /></div><h2 className="text-2xl font-bold text-earth-900">3. Information Sharing</h2></div>
 <h3 className="text-lg font-semibold text-earth-800 mb-3">3.1 We Share With:</h3><ul className="space-y-3 mb-6 text-earth-600"><li className="flex items-start gap-2"><span className="text-primary-500 mt-1">•</span><strong>Other users:</strong> Your listings, public profile, trust score, and verification badges</li><li className="flex items-start gap-2"><span className="text-primary-500 mt-1">•</span><strong>Agents:</strong> Your information for verification purposes</li><li className="flex items-start gap-2"><span className="text-primary-500 mt-1">•</span><strong>Payment processors:</strong> EcoCash, OneMoney for transaction processing</li><li className="flex items-start gap-2"><span className="text-primary-500 mt-1">•</span><strong>Regulatory authorities:</strong> When required by law</li></ul>
 <h3 className="text-lg font-semibold text-earth-800 mb-3">3.2 We Do NOT Share:</h3><ul className="space-y-3 mb-6 text-earth-600"><li className="flex items-start gap-2"><span className="text-primary-500 mt-1">•</span>Your phone number with other users (use platform chat)</li><li className="flex items-start gap-2"><span className="text-primary-500 mt-1">•</span>Your ID documents (except for verification with your consent)</li><li className="flex items-start gap-2"><span className="text-primary-500 mt-1">•</span>Your payment details (processed securely by partners)</li><li className="flex items-start gap-2"><span className="text-primary-500 mt-1">•</span>Your data with third-party marketers</li></ul></div>
 <div id="security" className="mb-12 scroll-mt-24 pt-8 border-t border-earth-100"><div className="flex items-center gap-3 mb-4"><div className="w-10 h-10 rounded-lg bg-primary-100 flex items-center justify-center"><Lock className="w-5 h-5 text-primary-600" /></div><h2 className="text-2xl font-bold text-earth-900">4. Data Security</h2></div><p className="text-earth-600 mb-4">4.1 We implement industry-standard security measures including:</p><ul className="space-y-2 mb-4 text-earth-600"><li className="flex items-start gap-2"><span className="text-primary-500 mt-1">•</span>Encryption in transit (TLS 1.3)</li><li className="flex items-start gap-2"><span className="text-primary-500 mt-1">•</span>Encryption at rest (AES-256)</li><li className="flex items-start gap-2"><span className="text-primary-500 mt-1">•</span>Regular security audits and penetration testing</li><li className="flex items-start gap-2"><span className="text-primary-500 mt-1">•</span>Access controls and authentication</li><li className="flex items-start gap-2"><span className="text-primary-500 mt-1">•</span>24/7 monitoring for suspicious activity</li></ul><p className="text-earth-600">4.2 However, no method of transmission over the internet is 100% secure. You use the platform at your own risk.</p></div>
 <div id="retention" className="mb-12 scroll-mt-24 pt-8 border-t border-earth-100"><div className="flex items-center gap-3 mb-4"><div className="w-10 h-10 rounded-lg bg-primary-100 flex items-center justify-center"><Trash2 className="w-5 h-5 text-primary-600" /></div><h2 className="text-2xl font-bold text-earth-900">5. Data Retention</h2></div><ul className="space-y-2 text-earth-600"><li className="flex items-start gap-2"><span className="text-primary-500 mt-1">•</span>Transaction records: 7 years (legal requirement)</li><li className="flex items-start gap-2"><span className="text-primary-500 mt-1">•</span>User accounts: Until account deletion request</li><li className="flex items-start gap-2"><span className="text-primary-500 mt-1">•</span>Verification documents: 7 years</li><li className="flex items-start gap-2"><span className="text-primary-500 mt-1">•</span>Chat messages: 2 years</li><li className="flex items-start gap-2"><span className="text-primary-500 mt-1">•</span>Session logs: 90 days</li></ul></div>
 <div id="rights" className="mb-12 scroll-mt-24 pt-8 border-t border-earth-100"><div className="flex items-center gap-3 mb-4"><div className="w-10 h-10 rounded-lg bg-primary-100 flex items-center justify-center"><UserX className="w-5 h-5 text-primary-600" /></div><h2 className="text-2xl font-bold text-earth-900">6. Your Rights</h2></div><p className="text-earth-600 mb-4">Under Zimbabwe's data protection laws, you have the right to:</p><ul className="space-y-2 mb-4 text-earth-600"><li className="flex items-start gap-2"><span className="text-primary-500 mt-1">•</span>Access your personal data</li><li className="flex items-start gap-2"><span className="text-primary-500 mt-1">•</span>Correct inaccurate data</li><li className="flex items-start gap-2"><span className="text-primary-500 mt-1">•</span>Delete your account and associated data</li><li className="flex items-start gap-2"><span className="text-primary-500 mt-1">•</span>Withdraw consent for data processing</li><li className="flex items-start gap-2"><span className="text-primary-500 mt-1">•</span>Data portability (receive your data in a structured format)</li></ul><p className="text-earth-600">To exercise these rights, contact us at privacy@zimagritrust.com</p></div>
 <div id="cookies" className="mb-12 scroll-mt-24 pt-8 border-t border-earth-100"><div className="flex items-center gap-3 mb-4"><div className="w-10 h-10 rounded-lg bg-primary-100 flex items-center justify-center"><Cookie className="w-5 h-5 text-primary-600" /></div><h2 className="text-2xl font-bold text-earth-900">7. Cookies & Tracking</h2></div><div className="space-y-3 text-earth-600"><p>7.1 We use essential cookies for platform operation (login, session management).</p><p>7.2 We use analytics cookies to improve our service (anonymous usage data).</p><p>7.3 We do not use third-party advertising cookies.</p><p>7.4 You can disable cookies in your browser settings, but some features may not work.</p></div></div>
 <div className="mb-12 pt-8 border-t border-earth-100"><h2 className="text-2xl font-bold text-earth-900 mb-4">8. Children's Privacy</h2><p className="text-earth-600">Our platform is not intended for users under 18 years old. We do not knowingly collect data from minors. If we discover a user under 18, we will delete their account immediately.</p></div>
<div className="mb-12 pt-8 border-t border-earth-100"><h2 className="text-2xl font-bold text-earth-900 mb-4">9. International Data Transfers</h2><p className="text-earth-600">Your data may be transferred to and processed in countries with different data protection laws. We ensure appropriate safeguards are in place for such transfers.</p></div>
<div className="mb-12 pt-8 border-t border-earth-100"><h2 className="text-2xl font-bold text-earth-900 mb-4">10. Changes to This Policy</h2><p className="text-earth-600">We will notify users of material changes via SMS, WhatsApp, and email. Continued use of the platform after changes constitutes acceptance of the revised policy.</p></div>
<div id="contact" className="scroll-mt-24 pt-8 border-t border-earth-100"><div className="flex items-center gap-3 mb-4"><div className="w-10 h-10 rounded-lg bg-primary-100 flex items-center justify-center"><Shield className="w-5 h-5 text-primary-600" /></div><h2 className="text-2xl font-bold text-earth-900">11. Contact Us</h2></div><div className="space-y-2 text-earth-600"><p>For privacy-related questions or data requests:</p><p><strong>Email:</strong> privacy@zimagritrust.com</p><p><strong>Phone:</strong> +263 71 735 8956</p><p><strong>Data Protection Officer:</strong> dpo@zimagritrust.com</p></div></div></div></div></div></div></section></div>);
}

export default PrivacyPolicy;
