export const theme = {
  colors: {
    green: '#1F6F43',
    gold: '#D9A441',
    brown: '#5B4334',
    sky: '#1677FF',
    orange: '#F37A45',
    red: '#C94242',
    white: '#FFFFFF',
    cream: '#F8F4EA',
    ink: '#102033',
    mist: '#EEF4FF',
    successTint: '#E6F6EC',
    warningTint: '#FFF5DF',
    dangerTint: '#FDECEC',
    gray: {
      100: '#F8FAFC',
      200: '#EEF2F6',
      300: '#D7DEE8',
      400: '#A8B4C3',
      500: '#7B8898',
      600: '#5D6978',
      700: '#455160',
      800: '#2B3645',
      900: '#16202C',
    },
    black: '#16202C',
    light: '#F8F4EA',
  },
  typography: {
    h1: { fontSize: 34, fontWeight: '800', letterSpacing: -0.6, lineHeight: 40 },
    h2: { fontSize: 29, fontWeight: '800', letterSpacing: -0.4, lineHeight: 35 },
    h3: { fontSize: 24, fontWeight: '700', letterSpacing: -0.2, lineHeight: 30 },
    h4: { fontSize: 20, fontWeight: '700', letterSpacing: -0.1, lineHeight: 26 },
    body: { fontSize: 16, fontWeight: '500', lineHeight: 24 },
    bodyLarge: { fontSize: 18, fontWeight: '500', lineHeight: 28 },
    caption: { fontSize: 14, fontWeight: '500', lineHeight: 20 },
    small: { fontSize: 12, fontWeight: '600', lineHeight: 16 },
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
    xxl: 48,
  },
  borderRadius: {
    xs: 4,
    sm: 10,
    md: 14,
    lg: 20,
    xl: 24,
    xxl: 30,
    round: 9999,
  },
  shadows: {
    xs: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.05,
      shadowRadius: 2,
      elevation: 1,
    },
    sm: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.06,
      shadowRadius: 6,
      elevation: 2,
    },
    md: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.1,
      shadowRadius: 14,
      elevation: 6,
    },
    lg: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 12 },
      shadowOpacity: 0.14,
      shadowRadius: 20,
      elevation: 10,
    },
    xl: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: 0.2,
      shadowRadius: 20,
      elevation: 12,
    },
  },
};

export const globalStyles = {
  container: {
    flex: 1,
    backgroundColor: theme.colors.gray[100],
  },
  header: {
    paddingTop: 60,
    paddingHorizontal: theme.spacing.lg,
    paddingBottom: theme.spacing.md,
  },
  title: {
    fontSize: theme.typography.h1.fontSize,
    fontWeight: theme.typography.h1.fontWeight,
    color: theme.colors.black,
    fontFamily: 'Poppins-Bold',
  },
  card: {
    backgroundColor: theme.colors.white,
    borderRadius: theme.borderRadius.lg,
    padding: theme.spacing.lg,
    ...theme.shadows.md,
    borderWidth: 1,
    borderColor: theme.colors.gray[200],
  },
  primaryBtn: {
    backgroundColor: theme.colors.green,
    borderRadius: theme.borderRadius.xl,
    paddingVertical: 18,
    paddingHorizontal: 20,
    alignItems: 'center',
    justifyContent: 'center',
    ...theme.shadows.md,
  },
  primaryBtnText: {
    color: theme.colors.white,
    fontSize: 16,
    fontWeight: '800',
    letterSpacing: 0.2,
  },
  badge: {
     paddingHorizontal: 12,
     paddingVertical: 4,
     borderRadius: theme.borderRadius.round,
     fontSize: 12,
     fontWeight: '700',
  }
};
