"""
Crop Classifier using YOLOv8 for Zimbabwean Agricultural Products

Model loading priority:
  1. Custom trained weights at ml_weights/crop_classifier.pt
     (trained on Kaggle agriculture-crops-dataset — classes loaded from class_map.json)
  2. Auto-downloaded YOLOv8n base model (general object detector)
  3. OpenCV colour-histogram fallback (no network required)
"""

import io
import json
import logging
import os
from pathlib import Path
from typing import Any, Dict, List, Tuple

import numpy as np
from PIL import Image

try:
    import cv2
    CV2_AVAILABLE = True
except ImportError:
    cv2 = None
    CV2_AVAILABLE = False

try:
    from ultralytics import YOLO
    YOLO_AVAILABLE = True
except ImportError:
    YOLO_AVAILABLE = False

logger = logging.getLogger(__name__)

# Paths
_CUSTOM_WEIGHTS  = Path("ml_weights/crop_classifier.pt")
_BASE_WEIGHTS    = Path("ml_weights/yolov8n.pt")
_ULTRALYTICS_DIR = Path("ml_weights")
_CLASS_MAP       = Path("data/training/data/kaggle_crops/class_map.json")


def _load_class_map() -> dict[str, str]:
    """Load {index: class_name} from class_map.json produced by the download script."""
    if _CLASS_MAP.exists():
        with open(_CLASS_MAP) as f:
            return json.load(f)
    return {}


class CropClassifier:
    """
    Crop classification using YOLOv8 or fallback to OpenCV colour analysis.
    Class names are loaded from class_map.json (generated by the Kaggle download script).
    """

    def __init__(self, model_path: str = None):
        self.model = None
        self.model_path = Path(model_path) if model_path else _CUSTOM_WEIGHTS
        self.confidence_threshold = 0.65
        # Load class map from dataset — no hardcoded crop list
        self._class_map: dict[str, str] = _load_class_map()
        self._class_names: list[str] = [
            self._class_map[str(i)] for i in range(len(self._class_map))
        ]
        self._load_model()

    @property
    def CROPS(self) -> dict[str, str]:
        """Backward-compat mapping of class names → class names for whatsapp_service."""
        if self._class_names:
            return {name: name for name in self._class_names}
        # Fallback if no trained model class-map is present yet
        return {
            "maize": "maize",
            "soya_beans": "soya_beans",
            "tomato": "tomato",
            "mango": "mango",
            "wheat": "wheat",
            "cotton": "cotton",
            "tobacco": "tobacco",
            "groundnuts": "groundnuts",
            "sorghum": "sorghum",
            "barley": "barley",
        }

    def _load_model(self) -> None:
        """
        Load model with three-tier fallback:
          1. Custom trained crop classifier weights
          2. YOLOv8n base model (auto-downloaded from Ultralytics on first run)
          3. OpenCV colour-histogram fallback (offline, no GPU needed)
        """
        if not YOLO_AVAILABLE:
            logger.info("Ultralytics not installed — using OpenCV fallback classifier.")
            return

        # Tier 1: custom trained weights
        if self.model_path.exists():
            try:
                self.model = YOLO(str(self.model_path))
                logger.info("CropClassifier | Loaded custom weights: %s", self.model_path)
                return
            except Exception as e:
                logger.warning("CropClassifier | Custom weights failed to load (%s) — trying base model.", e)

        # Tier 2: YOLOv8n base model (downloads ~6 MB once, then cached)
        try:
            _ULTRALYTICS_DIR.mkdir(parents=True, exist_ok=True)
            # Tell Ultralytics to save into our ml_weights folder
            os.environ.setdefault("YOLO_CONFIG_DIR", str(_ULTRALYTICS_DIR))

            if not _BASE_WEIGHTS.exists():
                logger.info("CropClassifier | Downloading YOLOv8n base model (~6 MB)...")
            self.model = YOLO(str(_BASE_WEIGHTS) if _BASE_WEIGHTS.exists() else "yolov8n.pt")
            # Save it to our weights dir for next time
            if not _BASE_WEIGHTS.exists():
                self.model.save(str(_BASE_WEIGHTS))
            logger.info("CropClassifier | Using YOLOv8n base model (general detector). "
                        "Train a crop-specific model and place it at %s for best results.", _CUSTOM_WEIGHTS)
        except Exception as e:
            logger.info("CropClassifier | YOLOv8n unavailable (%s) — using OpenCV fallback.", e)
            self.model = None
    
    def preprocess_image(self, image_data: bytes) -> np.ndarray:
        """
        Convert uploaded image bytes to format suitable for model
        """
        # Read image from bytes
        image = Image.open(io.BytesIO(image_data))
        
        # Convert to RGB if needed
        if image.mode != 'RGB':
            image = image.convert('RGB')
        
        # Resize for model (YOLO typically expects 640x640)
        image = image.resize((640, 640))
        
        # Convert to numpy array
        return np.array(image)
    
    async def classify(self, image_data: bytes) -> Dict[str, Any]:
        """
        Classify crop from image
        Returns: {
            "success": bool,
            "crop_type": str,
            "confidence": float,
            "grade": str,
            "health_status": str,
            "recommendations": list
        }
        """
        try:
            # Preprocess image
            image = self.preprocess_image(image_data)
            
            # Use YOLO model if available
            if self.model:
                results = self.model(image, verbose=False)
                return self._parse_yolo_results(results)
            else:
                # Fallback to simple feature detection
                return self._fallback_classify(image)
                
        except Exception as e:
            logger.error(f"Classification error: {e}")
            return {
                "success": False,
                "error": str(e),
                "crop_type": "unknown",
                "confidence": 0.0,
                "grade": "Unknown",
                "health_status": "Unable to analyze",
                "recommendations": ["Please ensure the image is clear and well-lit"]
            }
    
    def _parse_yolo_results(self, results) -> Dict[str, Any]:
        """
        Parse YOLO detection results
        """
        result = results[0]
        
        if len(result.boxes) == 0:
            return {
                "success": False,
                "crop_type": "unknown",
                "confidence": 0.0,
                "grade": "Unknown",
                "health_status": "No crop detected",
                "recommendations": ["Take a clearer photo of the crop", "Ensure the crop is centered"]
            }
        
        # Get highest confidence detection
        top_box = result.boxes[0]
        class_id = int(top_box.cls[0])
        confidence = float(top_box.conf[0])
        
        # Map class ID to crop name from dataset class_map
        crop_type = self._class_names[class_id] if class_id < len(self._class_names) else "unknown"
        crop_name = crop_type.replace("_", " ").title()
        
        # Grade estimation based on visual features
        grade = self._estimate_grade(result, crop_type)
        
        # Health assessment
        health_status, issues = self._assess_health(result, crop_type)
        
        return {
            "success": confidence >= self.confidence_threshold,
            "crop_type": crop_type,
            "crop_name": crop_name,
            "confidence": confidence,
            "grade": grade,
            "health_status": health_status,
            "health_issues": issues,
            "recommendations": self._get_recommendations(crop_type, grade, health_status),
            "detected_features": self._extract_features(result, crop_type)
        }
    
    def _fallback_classify(self, image: np.ndarray) -> Dict[str, Any]:
        """
        Fallback classification using colour heuristics (PIL/numpy, no cv2 required)
        """
        if CV2_AVAILABLE:
            hsv = cv2.cvtColor(image, cv2.COLOR_RGB2HSV)
            hue_mean = np.mean(hsv[:, :, 0])
        else:
            # Approximate HSV hue via numpy: use R-G-B ratios
            r, g, b = image[:, :, 0].astype(float), image[:, :, 1].astype(float), image[:, :, 2].astype(float)
            max_c = np.maximum(np.maximum(r, g), b)
            min_c = np.minimum(np.minimum(r, g), b)
            delta = max_c - min_c + 1e-6
            hue = np.where(max_c == r, (g - b) / delta % 6,
                  np.where(max_c == g, (b - r) / delta + 2,
                                       (r - g) / delta + 4)) * 60
            hue_mean = float(np.mean(hue))
            # Remap 0-360 to 0-180 to match OpenCV convention
            hue_mean = hue_mean / 2
        
        # Determine crop type by dominant color
        if 35 <= hue_mean <= 85:
            crop_type = "maize"
            confidence = 0.70
        elif 20 <= hue_mean < 35:
            crop_type = "soya_beans"
            confidence = 0.65
        elif 0 <= hue_mean < 15 or 165 <= hue_mean <= 180:
            crop_type = "tomato"
            confidence = 0.68
        else:
            crop_type = "unknown"
            confidence = 0.40
        
        crop_name = crop_type.replace("_", " ").title()
        
        return {
            "success": confidence >= self.confidence_threshold,
            "crop_type": crop_type,
            "crop_name": crop_name,
            "confidence": confidence,
            "grade": "Standard",
            "health_status": "Visible analysis limited",
            "health_issues": [],
            "recommendations": ["For better accuracy, please use the mobile app with camera access"],
            "detected_features": {"method": "fallback_color_analysis"}
        }
    
    def _estimate_grade(self, result, crop_type: str) -> str:
        """
        Estimate grade based on visual features
        Returns: Grade A, Grade B, Grade C, or Standard
        """
        # This is simplified - in production, train a grading model
        # For now, use confidence as proxy for quality
        confidence = float(result.boxes[0].conf[0]) if result.boxes else 0.5
        
        if confidence > 0.85:
            return "Grade A"
        elif confidence > 0.70:
            return "Grade B"
        elif confidence > 0.55:
            return "Grade C"
        else:
            return "Standard"
    
    def _assess_health(self, result, crop_type: str) -> Tuple[str, List[str]]:
        """
        Assess crop health from image
        Returns: (health_status, list_of_issues)
        """
        # Placeholder - implement actual disease detection
        # For now, return healthy if confidence is high
        confidence = float(result.boxes[0].conf[0]) if result.boxes else 0.5
        
        if confidence > 0.75:
            return "Healthy", []
        elif confidence > 0.60:
            return "Minor blemishes detected", ["Surface imperfections visible"]
        else:
            return "Quality concerns detected", ["Image quality poor", "Possible damage visible"]
    
    def _extract_features(self, result, crop_type: str) -> Dict[str, Any]:
        """
        Extract specific features from the crop image
        """
        features = {
            "crop_type": crop_type,
            "detection_confidence": float(result.boxes[0].conf[0]) if result.boxes else 0,
        }
        
        # Add crop-specific features
        if crop_type == "maize":
            features["kernel_visibility"] = "visible" if result.boxes else "unclear"
        elif crop_type == "mango":
            features["ripeness_indicators"] = "visible" if result.boxes else "unclear"
        elif crop_type == "tomato":
            features["color_uniformity"] = "good" if result.boxes[0].conf[0] > 0.8 else "variable"
        
        return features
    
    def _get_recommendations(self, crop_type: str, grade: str, health_status: str) -> List[str]:
        """
        Generate recommendations based on analysis
        """
        recommendations = []
        
        if grade == "Grade C":
            recommendations.append("Consider improving crop quality for better pricing")
        
        if "blemishes" in health_status.lower():
            recommendations.append("Sort out damaged produce before listing")
        
        # Add standard recommendations
        recommendations.append("Take clear, well-lit photos for better buyer interest")
        
        return recommendations


class GradeEstimator:
    """
    Estimate crop grade from images using quality metrics
    """
    
    def __init__(self):
        self.grade_thresholds = {
            "Grade A": 0.85,
            "Grade B": 0.70,
            "Grade C": 0.55
        }
    
    async def estimate(self, image: np.ndarray, crop_type: str) -> Dict[str, Any]:
        """
        Estimate grade of crop
        """
        # Calculate quality metrics
        sharpness = self._calculate_sharpness(image)
        color_uniformity = self._calculate_color_uniformity(image)
        
        # Combined score
        quality_score = (sharpness * 0.4 + color_uniformity * 0.6)
        
        # Determine grade
        if quality_score >= 0.85:
            grade = "Grade A"
            description = "Premium quality - excellent appearance"
        elif quality_score >= 0.70:
            grade = "Grade B"
            description = "Good quality - minor imperfections"
        elif quality_score >= 0.55:
            grade = "Grade C"
            description = "Standard quality - some imperfections visible"
        else:
            grade = "Standard"
            description = "Basic quality - review recommended"
        
        return {
            "grade": grade,
            "description": description,
            "quality_score": quality_score,
            "sharpness": sharpness,
            "color_uniformity": color_uniformity
        }
    
    def _calculate_sharpness(self, image: np.ndarray) -> float:
        """Calculate image sharpness using Laplacian variance"""
        if CV2_AVAILABLE:
            gray = cv2.cvtColor(image, cv2.COLOR_RGB2GRAY)
            laplacian = cv2.Laplacian(gray, cv2.CV_64F)
            variance = laplacian.var()
        else:
            # Approximate via numpy gradient
            gray = np.mean(image, axis=2)
            gy, gx = np.gradient(gray)
            variance = float(np.var(gx) + np.var(gy))
        return min(variance / 500, 1.0)
    
    def _calculate_color_uniformity(self, image: np.ndarray) -> float:
        """Calculate color uniformity (lower std dev = more uniform)"""
        if CV2_AVAILABLE:
            hsv = cv2.cvtColor(image, cv2.COLOR_RGB2HSV)
            hue_std = np.std(hsv[:, :, 0])
        else:
            hue_std = float(np.std(image[:, :, 0].astype(float)))
        return max(0, 1 - (hue_std / 90))


# Singleton instance
crop_classifier = CropClassifier()
grade_estimator = GradeEstimator()
